# Generated by Django 5.2.11 on 2026-03-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('water', '0006_rename_amount_due_bill_total_bill_bill_dustbin_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dustbins', to='water.site')),
            ],
        ),
        migrations.CreateModel(
            name='DustbinBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dustbin_bills', to='water.apartment')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dustbin_bills', to='water.bill')),
            ],
        ),
    ]
