# Generated by Django 5.2.11 on 2026-03-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
    ]