# Generated by Django 5.2.11 on 2026-03-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_delete_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
