# Generated by Django 5.2.11 on 2026-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_apartment_is_active_apartment_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
