# Generated by Django 5.2.11 on 2026-03-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_add_billoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
