# Generated by Django 5.2.11 on 2026-03-12 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_apartment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='login_attempts',
        ),
    ]
