# Generated by Django 5.2.11 on 2026-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_bill_currency_bill_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bill',
            name='volume_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
