# Generated by Django 5.2.11 on 2026-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_remove_apartment_login_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amount_due',
            new_name='total_bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='dustbin_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
