# Generated by Django 5.2.11 on 2026-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_rename_amount_due_bill_total_bill_bill_dustbin_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
