# Generated by Django 5.2.11 on 2026-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User (Resident)'), ('block_admin', 'Block Administrator'), ('superuser', 'Superuser')], default='user', max_length=20),
        ),
    ]
