# Generated by Gemini Code Assist

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for new bills and payments.'),
        ),
    ]